export const SELECT_POKEMON_SUCCESS = 'SELECT_POKEMON_SUCCESS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';

export const CAUGHT_POKEMON = 'CAUGHT_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';

export const CHANGE_THEME = 'CHANGE_THEME';
